services:
- docker

language: ruby

branches:
  only:
  - master
  - development
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install: skip

script:
- echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
- ./.travis.sh
